name: Add-on Validations

on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main ]

jobs:
  addon-validations:
    if: github.repository == 'anxdpanic/plugin.video.playthis'

    runs-on: ubuntu-latest
    name: Add-on Validations

    steps:
      - name: Checkout Add-on
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/xbmc/addon-check.git

      - name: Kodi Add-on Checker (Jarvis)
        id: kodi-addon-checker-jarvis
        run: |
          kodi-addon-checker ${{ github.event.repository.name }} --branch=jarvis

      - name: Staging for Matrix
        run: |
          git reset
          git checkout .
          git clean -fdx
          git apply .patches/matrix.patch
        working-directory: ${{ github.event.repository.name }}

      - name: Kodi Add-on Checker (Matrix)
        id: kodi-addon-checker-matrix
        run: |
          kodi-addon-checker ${{ github.event.repository.name }} --branch=matrix
